blank_issues_enabled: true
contact_links:
  - name: How to Contribute
    url: https://github.com/YigtyORG/Ywando/blob/master/CONTRIBUTING.md
    about: Please check this page before you submit an issue.
  - name: 貢献方法
    url: https://github.com/YigtyORG/Ywando/blob/master/CONTRIBUTING.md
    about: Issue を作成する前に確認してください。
