# ***********************************************************
# * TakymLib                                                *
# * Copyright (C) 2020-2021 Yigty.ORG; all rights reserved. *
# * Copyright (C) 2020-2021 Takym.                          *
# *                                                         *
# * distributed under the MIT License.                      *
# ***********************************************************

name: "Benchmark"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Benchmark:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2.4.0
      with:
        submodules: recursive
    - name: Setup .NET
      uses: actions/setup-dotnet@v1.8.2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore TakymLib.sln
    # Build
    - name: Build (Target Programs)
      run: dotnet build -c ReleaseW --no-restore
    - name: Build (Testing Environment)
      run: dotnet build -c BenchmarkW --no-restore
    # Test
    - name: Test
      run: dotnet test -c BenchmarkW --no-build --verbosity normal
    # Upload Artifacts
    - name: Save Benchmarks Results
      uses: actions/upload-artifact@v2
      with:
        name: benchmarks-results
        path: tests/bin/Benchmark/**
