name: "BuildTest"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  BuildTest:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, windows-2019, ubuntu-latest, ubuntu-20.04, ubuntu-18.04, ubuntu-16.04, macos-latest, macos-10.15 ]
        config: [ Debug, Release ]
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.201
    - name: Restore dependencies
      run: dotnet restore TakymLib.sln
    # Build
    - name: Build
      run: dotnet build -c ${{ matrix.config }} --no-restore
    # Test
    - name: Test
      run: dotnet test -c ${{ matrix.config }} --no-build --verbosity normal
