name: "BuildTest"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  BuildTest:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest, macos-latest ]
        runtime: [ "net5.0", "netcoreapp3.1", "netstandard2.1", "net48" ]
        config: [ Debug, Release ]
    steps:
    - uses: actions/checkout@v2.3.4
    - name: Setup .NET
      uses: actions/setup-dotnet@v1.8.0
      with:
        dotnet-version: 5.0.201
    - name: Restore dependencies
      run: dotnet restore TakymLib.sln
    # Build
    - name: Build
      run: dotnet build -r ${{ matrix.runtime }} -c ${{ matrix.config }} --no-restore
    # Test
    - name: Test
      run: dotnet test -r ${{ matrix.runtime }} -c ${{ matrix.config }} --no-build --verbosity normal
