name: .NET - Debug (Ubuntu)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0
    - name: Restore dependencies
      run: dotnet restore TakymLib.sln
    - name: Build
      run: dotnet build --configuration Debug --no-restore
    - name: Test
      run: dotnet test --configuration Debug --no-build --verbosity normal
